export const AUDIT_ACTIONS = {
  IB_CREATE:            'IB_CREATE',
  IB_UPDATE:            'IB_UPDATE',
  IB_PROFILE_UPDATE:    'IB_PROFILE_UPDATE',
  IB_DEACTIVATE:        'IB_DEACTIVATE',
  IB_RESTORE:           'IB_RESTORE',
  IB_PASSWORD_RESET:    'IB_PASSWORD_RESET',
  REBATE_CONFIG_UPDATE: 'REBATE_CONFIG_UPDATE',
  TRANSACTION_CREATE:   'TRANSACTION_CREATE',
  TRANSACTION_BATCH:    'TRANSACTION_BATCH_CREATE',
  TRANSACTION_DELETE:   'TRANSACTION_DELETE',
  PASSWORD_CHANGE:      'PASSWORD_CHANGE',
  PAYOUT_REQUESTED:     'PAYOUT_REQUESTED',
  PAYOUT_APPROVED:      'PAYOUT_APPROVED',
  PAYOUT_REJECTED:      'PAYOUT_REJECTED',
} as const;

export type AuditAction = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS];

